<?php
use PbPWp\Core\Entity;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-06 at 19:55:26.
 */
class EntityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Entity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Entity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Entity::getContents
     * @todo   Implement testGetContents().
     */
    public function testGetContents() {
        $this->assertEquals("1", "2");
    }

    /**
     * @covers Entity::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Entity::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
