<?php

use pbpCore\implementations\WpPostEntityRepository;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-06 at 19:55:26.
 */
class EntityTest extends WP_UnitTestCase {

    /**
     * @var Entity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new WpPostEntityRepository();
        parent::setUp();
    }

    /**
     * @covers WpPostEntityRepository::getEntityById
     * @todo   Implement testGetContents().
     */
    public function testGetEntityById() {
        $post_id = $this->factory->post->create(array( 
            'post_title' => 'Chapter 1, Scene 3' ));

        $result = $this->object->getEntityById($post_id);
   
        $this->assertEquals($post_id, $result->getId());
        $this->assertEquals("Chapter 1, Scene 3", $result->getTitle());
    }
    
    /**
     * @covers WpPostEntityRepository::getEntitiesByIds
     * @todo   Implement testGetContents().
     */
    public function testGetEntitiesById() {
         $post_id = $this->factory->post->create();
         
        $results = $this->object->getEntitiesById([$post_id]);
        
        $this->assertEquals(1, count($results));
    }
}