<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-06 at 19:55:26.
 */
class Sample_Tests extends PHPUnit_Framework_TestCase {

    public function testSampleAssert() {
          $this->assertTrue(true);
    }
}